djangoLvl4/sample_project/app1/urls.py
from django.conf.urls import url
from app1 import views

#TEMPLATE TAGGING
app_name = 'app1'

urlpatterns=[
    url(r'^relative/$', views.relative, name='relative'),
    url(r'^other/$', views.other, name = 'other'),
]

djangoLvl4/sample_project/sample_project/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from app1 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name="index"),
    url(r'^app1/', include("app1.urls"), name='app1'),
]

djangoLvl4/sample_project/app1/models.py
from django.db import models

# Create your models here.

djangoLvl4/sample_project/app1/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    my_dict = {'text':'hello World', 'number': 100}
    return render(request,'app1/index.html',context = my_dict)

def base(request):
    return render(request,'app1/base.html', context={'ewan':''})

def other(request):
    return render(request,'app1/other.html', context={'ewan':''})

def relative(request):
    return render(request,'app1/app1.html', context={'ewan':''})

djangoLvl4/sample_project/templates/app1/app1.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>This is the APP1 page</title>
  </head>
  <body>
<h1>This is the APP1 page, RELATIVE URL TEMPLATES</h1>
<a href="{% url 'app1:other'%}">THIS IS OTHER PAGE</a>
<a href="{% url 'admin:index' %}">ADMIN ENGKK</a>
<a href="{% url 'index' %}">INDEX LINK</a>
  </body>
</html>

djangoLvl4/sample_project/templates/app1/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
     rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous">
    <title>This is the BASE page</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{url "index"}">DJANGO</a>
        <a class="nav-item nav-link" href="{url "admin:index"}">Admin</a>
        <a class="nav-item nav-link" href="">Other</a>
      </div>
    </nav>

    <div class="container">
    {% block body_block %}
    <!-- {# Anything outside of this will be inherited if you use extend.#} -->
    {% endblock %}
    </div>

  </body>
</html>

djangoLvl4/sample_project/templates/app1/index.html
<!DOCTYPE html>
{% extends "app1/base.html" %}
{% load my_templates %}


    {% block body_block%}

      <h1>hiii!</h1>
      <!-- <h1>This is the index.html page</h1> -->
    <h1>{{ text|upper}}</h1>
    <h1>{{ number|add:"99"}}</h1>
    {% endblock %}

djangoLvl4/sample_project/templates/app1/other.html
<!DOCTYPE html>
{% extends "app1/base.html"%}
  {% block body_block%}
    <h1>HEMLO, THIS IS THE OTHER PAGE</h1>
    <h2>I inherit base html</h2>
    {% endblock %}